---
AWSTemplateFormatVersion: "2020-11-08"

# Parameters Section
Parameters:
  UserAuthTableName:
    Type: String
    Default: user_auth
  DrawerTableName:
    Type: String
    Default: drawer_table

Resources:
  UserAuthTable:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      TableName: !Ref UserAuthTableName
      AttributeDefinitions:
        - AttributeName: user_id
          AttributeType: S
      KeySchema:
        - AttributeName: user_id
          KeyType: HASH
      LocalSecondaryIndexes:
        - IndexName: refNumLSI
          KeySchema:
            - AttributeName: user_id
              KeyType: HASH
          Projection:
            ProjectionType: ALL
        - IndexName: refInceptionDateLSI
          KeySchema:
            - AttributeName: user_id
              KeyType: HASH
          Projection:
            ProjectionType: ALL
  DrawerTable:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      TableName: !Ref DrawerTableName
      AttributeDefinitions:
        - AttributeName: merchant_id
          AttributeType: S
        - AttributeName: drawer_id
          AttributeType: S
      KeySchema:
        - AttributeName: merchant_id
          KeyType: HASH
        - AttributeName: drawer_id
          KeyType: RANGE
      LocalSecondaryIndexes:
        - IndexName: refNumLSI
          KeySchema:
            - AttributeName: merchant_id
              KeyType: HASH
            - AttributeName: drawer_id
               KeyType: RANGE
          Projection:
            ProjectionType: ALL
        - IndexName: refInceptionDateLSI
          KeySchema:
            - AttributeName: merchant_id
              KeyType: HASH
            - AttributeName: drawer_id
               KeyType: RANGE
          Projection:
            ProjectionType: ALL
  

Outputs:
  UserAuthTableName:
    Value: !Ref UserAuthTable # resource name
    Description: UserAuthTable Table Name
    Export:
      Name: !Sub ${AWS::StackName}-UserAuthTableName
  DrawerTableName:
    Value: !Ref DrawerTable # resource name
    Description: DrawerTable Table Name
    Export:
      Name: !Sub ${AWS::StackName}-DrawerTableName
